/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yyd_wilsonplayer_jni_MediaPlay */

#ifndef _Included_com_yyd_wilsonplayer_jni_MediaPlay
#define _Included_com_yyd_wilsonplayer_jni_MediaPlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yyd_wilsonplayer_jni_MediaPlay
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yyd_wilsonplayer_jni_MediaPlay_play
  (JNIEnv *, jclass, jstring,jobject);

JNIEXPORT void JNICALL Java_com_yyd_wilsonplayer_jni_MediaPlay_test
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
